# Generated by Django 5.0.7 on 2024-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0002_todoitem_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(help_text='Enter the task', max_length=100)),
                ('Date', models.DateField(help_text='Enter the date of the task')),
                ('Time', models.TimeField(help_text='Enter the time of the task')),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
